/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconGitlab: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_40_2701)">
        <path
          d="M22.6499 14.39L11.9999 22.13L1.3499 14.39C1.20713 14.285 1.10122 14.1375 1.04733 13.9687C0.99345 13.7998 0.994348 13.6183 1.0499 13.45L2.2699 9.66996L4.7099 2.15996C4.73357 2.09877 4.77124 2.04397 4.8199 1.99996C4.89914 1.92758 5.00258 1.88745 5.1099 1.88745C5.21722 1.88745 5.32066 1.92758 5.3999 1.99996C5.45128 2.04963 5.48914 2.11158 5.5099 2.17996L7.9499 9.66996H16.0499L18.4899 2.15996C18.5136 2.09877 18.5512 2.04397 18.5999 1.99996C18.6791 1.92758 18.7826 1.88745 18.8899 1.88745C18.9972 1.88745 19.1007 1.92758 19.1799 1.99996C19.2313 2.04963 19.2691 2.11158 19.2899 2.17996L21.7299 9.68996L22.9999 13.45C23.0504 13.6234 23.0437 13.8086 22.9806 13.9779C22.9176 14.1473 22.8016 14.2918 22.6499 14.39V14.39Z"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_40_2701">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
};

IconGitlab.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
