/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconSquareFacebook: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_517_25377)">
        <path
          d="M24 0L0 6.41942e-05V24L12.8203 24V14.7187H9.70312V11.0859H12.8203V8.41241C12.8203 5.31207 14.7131 3.62457 17.4787 3.62457C18.8033 3.62457 19.9416 3.72327 20.2734 3.7674V7.00781H18.3664C16.8616 7.00781 16.5703 7.72284 16.5703 8.77221V11.0859H20.168L19.6992 14.7187H16.5703V24L24 24V0Z"
          fill={color}
        />
      </g>
      <defs>
        <clipPath id="clip0_517_25377">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
};

IconSquareFacebook.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
