/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconTechRadio: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M12 14C13.1046 14 14 13.1046 14 12C14 10.8954 13.1046 10 12 10C10.8954 10 10 10.8954 10 12C10 13.1046 10.8954 14 12 14Z"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M16.2401 7.75993C16.7979 8.31717 17.2405 8.9789 17.5424 9.70729C17.8444 10.4357 17.9998 11.2164 17.9998 12.0049C17.9998 12.7934 17.8444 13.5742 17.5424 14.3026C17.2405 15.031 16.7979 15.6927 16.2401 16.2499M7.76006 16.2399C7.2022 15.6827 6.75965 15.021 6.4577 14.2926C6.15576 13.5642 6.00034 12.7834 6.00034 11.9949C6.00034 11.2064 6.15576 10.4257 6.4577 9.69729C6.75965 8.9689 7.2022 8.30717 7.76006 7.74993M19.0701 4.92993C20.9448 6.80521 21.9979 9.34829 21.9979 11.9999C21.9979 14.6516 20.9448 17.1947 19.0701 19.0699M4.93006 19.0699C3.05535 17.1947 2.0022 14.6516 2.0022 11.9999C2.0022 9.34829 3.05535 6.80521 4.93006 4.92993"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
};

IconTechRadio.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
