/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconTechPower: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M18.3601 6.63989C19.6185 7.89868 20.4754 9.50233 20.8224 11.2481C21.1694 12.9938 20.991 14.8033 20.3098 16.4476C19.6285 18.092 18.4749 19.4974 16.9949 20.4862C15.515 21.475 13.775 22.0028 11.9951 22.0028C10.2152 22.0028 8.47527 21.475 6.99529 20.4862C5.51532 19.4974 4.36176 18.092 3.68049 16.4476C2.99921 14.8033 2.82081 12.9938 3.16784 11.2481C3.51487 9.50233 4.37174 7.89868 5.63012 6.63989"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M12 2V12"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
};

IconTechPower.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
