/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconDownloadCloud: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_40_2615)">
        <path
          d="M8 17L12 21L16 17"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12 12V21"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M20.8801 18.0901C21.7494 17.4787 22.4014 16.6062 22.7413 15.5992C23.0813 14.5922 23.0915 13.5031 22.7705 12.4899C22.4494 11.4767 21.8139 10.5921 20.9561 9.96462C20.0983 9.33709 19.0629 8.99922 18.0001 9.00006H16.7401C16.4393 7.82793 15.8765 6.7393 15.0942 5.81614C14.3118 4.89297 13.3302 4.15932 12.2233 3.67041C11.1163 3.1815 9.9129 2.95008 8.70358 2.99357C7.49426 3.03706 6.31057 3.35433 5.24161 3.92148C4.17265 4.48864 3.24628 5.2909 2.53224 6.26788C1.81821 7.24487 1.33511 8.3711 1.11932 9.5618C0.903525 10.7525 0.960665 11.9767 1.28643 13.1421C1.6122 14.3075 2.19811 15.3838 3.00005 16.2901"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_40_2615">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
};

IconDownloadCloud.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
