/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconSymbolTwitter: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_517_25411)">
        <path
          d="M21.534 7.113C22.51 6.42 23.331 5.555 24 4.559V4.558C23.107 4.949 22.157 5.209 21.165 5.335C22.185 4.726 22.964 3.769 23.33 2.616C22.379 3.183 21.329 3.583 20.21 3.807C19.307 2.845 18.02 2.25 16.616 2.25C13.892 2.25 11.699 4.461 11.699 7.171C11.699 7.561 11.732 7.936 11.813 8.293C7.723 8.093 4.103 6.133 1.671 3.146C1.247 3.883 0.997 4.726 0.997 5.633C0.997 7.337 1.874 8.847 3.183 9.722C2.392 9.707 1.617 9.477 0.96 9.116V9.17C0.96 11.561 2.665 13.547 4.902 14.005C4.501 14.115 4.065 14.167 3.612 14.167C3.297 14.167 2.979 14.149 2.681 14.083C3.318 16.031 5.128 17.464 7.278 17.511C5.604 18.82 3.478 19.609 1.177 19.609C0.774 19.609 0.387 19.591 0 19.542C2.18 20.947 4.762 21.75 7.548 21.75C16.231 21.75 21.89 14.506 21.534 7.113Z"
          fill={color}
        />
      </g>
      <defs>
        <clipPath id="clip0_517_25411">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
};

IconSymbolTwitter.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
