/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconSymbolLinkedin: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_517_25414)">
        <path
          d="M23.994 24V23.999H24V15.197C24 10.891 23.073 7.57397 18.039 7.57397C15.619 7.57397 13.995 8.90198 13.332 10.161H13.262V7.97597H8.48901V23.999H13.459V16.065C13.459 13.976 13.855 11.956 16.442 11.956C18.991 11.956 19.029 14.34 19.029 16.199V24H23.994Z"
          fill={color}
        />
        <path d="M0.395996 7.97705H5.372V24H0.395996V7.97705Z" fill={color} />
        <path
          d="M2.882 0C1.291 0 0 1.291 0 2.882C0 4.473 1.291 5.791 2.882 5.791C4.473 5.791 5.764 4.473 5.764 2.882C5.763 1.291 4.472 0 2.882 0V0Z"
          fill={color}
        />
      </g>
      <defs>
        <clipPath id="clip0_517_25414">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
};

IconSymbolLinkedin.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
