/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconWeatherCloudSnow: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <g clipPath="url(#clip0_40_3132)">
        <path
          d="M20 17.58C21.0513 17.1195 21.9121 16.3115 22.4381 15.2915C22.9641 14.2715 23.1232 13.1016 22.8886 11.9781C22.6541 10.8547 22.0402 9.84617 21.1501 9.12179C20.2599 8.39742 19.1477 8.00131 18 7.99996H16.74C16.4231 6.77248 15.8189 5.63791 14.9773 4.68976C14.1358 3.74161 13.081 3.00703 11.8998 2.54658C10.7186 2.08612 9.44494 1.91297 8.18372 2.0414C6.92249 2.16983 5.70984 2.59615 4.64573 3.28524C3.58161 3.97433 2.6965 4.90644 2.06334 6.00475C1.43018 7.10307 1.06711 8.33613 1.00404 9.60231C0.940984 10.8685 1.17974 12.1315 1.70064 13.2873C2.22153 14.4431 3.00965 15.4585 4.00003 16.25"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M8 16H8.01"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M8 20H8.01"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12 18H12.01"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M12 22H12.01"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M16 16H16.01"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
        <path
          d="M16 20H16.01"
          stroke={color}
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </g>
      <defs>
        <clipPath id="clip0_40_3132">
          <rect width="24" height="24" fill={color} />
        </clipPath>
      </defs>
    </svg>
  );
};

IconWeatherCloudSnow.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
