import { Nunito } from 'next/font/google';

import './global.css';
import { Providers } from './providers';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
});

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'uk' }];
}

export const metadata = {
  title: 'Welcome to webapp',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../locales/${locale}.json`)).default;
  } catch (error) {
    console.log(error)
    // notFound();
  }

  return (
    <html lang={locale} className={`${nunito.variable} font-sans`}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
