import { PropsWithChildren } from 'react';

import { PageLayout } from '../../../src/components/home/page-layout';

export const metadata = {
  title: 'Welcome to Homepage',
  description: 'Generated by me',
};

export default function HomeLayout({ children }: PropsWithChildren) {
  return <PageLayout>{children}</PageLayout>
}
